import { Metadata } from "next"


export const metadata : Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        margin: 0,
        padding: 0,
        fontFamily: 'Arial, sans-serif',
        backgroundColor: '#f4f4f4',
        color: '#333',
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
      }}>
        <header style={{
          backgroundColor: '#007acc',
          padding: '1rem 2rem',
          color: '#fff',
          boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
        }}>
          <h1 style={{
            margin: 0,
            fontSize: '1.5rem',
            fontWeight: 'bold',
            textAlign: 'center',
          }}>
            My Website Header
          </h1>
        </header>

        <main style={{
          flex: '1',
          padding: '2rem',
          maxWidth: '1200px',
          margin: '0 auto',
          boxSizing: 'border-box',
        }}>
          {children}
        </main>
        
        <footer style={{
          backgroundColor: '#007acc',
          padding: '2rem',
          color: '#fff',
          textAlign: 'center',
          marginTop: 'auto',
          boxShadow: '0 -4px 8px rgba(0, 0, 0, 0.1)',
        }}>
          <p style={{ margin: 0 }}>© 2024 My Website. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
